export async function exportComplaintPDF(incidentData, analysisData, complaintText) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  const pageW = 210
  const margin = 20
  const contentW = pageW - margin * 2
  let y = margin

  const addLine = (text, size = 10, bold = false, color = [30, 30, 30]) => {
    doc.setFontSize(size)
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.setTextColor(...color)
    const lines = doc.splitTextToSize(text, contentW)
    lines.forEach(line => {
      if (y > 270) { doc.addPage(); y = margin }
      doc.text(line, margin, y)
      y += size * 0.5
    })
    y += 2
  }

  const addDivider = () => {
    doc.setDrawColor(220, 220, 220)
    doc.line(margin, y, pageW - margin, y)
    y += 5
  }

  // Header
  doc.setFillColor(232, 52, 26)
  doc.rect(0, 0, pageW, 18, 'F')
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.text('FRAUDGUARD AI — CYBER FRAUD COMPLAINT', margin, 12)
  y = 28

  addLine(`Date: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}`, 10, false, [80, 80, 80])
  addLine(`Reference ID: FG-${Date.now().toString().slice(-8)}`, 10, false, [80, 80, 80])
  y += 2

  addDivider()
  addLine('VICTIM DETAILS', 11, true, [232, 52, 26])
  y += 1
  addLine(`Name: ${incidentData.name}`)
  addLine(`UPI / Contact: ${incidentData.contact}`)
  addLine(`Bank: ${incidentData.bank}`)
  y += 2

  addDivider()
  addLine('TRANSACTION DETAILS', 11, true, [232, 52, 26])
  y += 1
  addLine(`Amount Lost: ₹${Number(incidentData.amount).toLocaleString('en-IN')}`)
  addLine(`Transaction ID / UTR: ${incidentData.txnId}`)
  addLine(`Date of Incident: ${new Date().toLocaleDateString('en-IN')}`)
  y += 2

  addDivider()
  addLine('AI FRAUD ANALYSIS', 11, true, [232, 52, 26])
  y += 1
  addLine(`Fraud Type: ${analysisData.fraudType} — ${analysisData.subType}`)
  addLine(`Severity: ${analysisData.severity?.toUpperCase()}`)
  addLine(`Recovery Probability: ${analysisData.recoveryScore}%`)
  addLine(`Classification: ${analysisData.fraudDetails}`)
  y += 2

  addDivider()
  addLine('FORMAL COMPLAINT', 11, true, [232, 52, 26])
  y += 1
  addLine(complaintText, 10, false, [30, 30, 30])

  y += 4
  addDivider()
  addLine('This complaint was auto-generated by FraudGuard AI. File this at cybercrime.gov.in and your bank\'s fraud helpline.', 9, false, [120, 120, 120])
  addLine('National Cyber Crime Helpline: 1930 | RBI Ombudsman: 14448', 9, false, [120, 120, 120])

  doc.save(`FraudGuard_Complaint_${Date.now()}.pdf`)
}
